ExtensibleSaveFormat/ExtendedSave.cs
ExtensibleSaveFormat/Hooks.cs

Hooks and callbacks were implemented when a scene is loaded/imported/saved in CharaStudio.
Renaming of some already existing functions had to be done to keep readability and logic in the code.
Additional data is added at the end of the file, after everything else was written.
MessagePackSerializer was used as well in this case to be able to keep using the already existing class "PluginData".
Manual patching had to be done for scene loading because I didn't find a way to automatically patch a function with an out/ref parameter.
Sorry I made a typo in the name of the commit.

Implemented hooks and callbacks in ExtensibleSaveFormat for CharaStudio scenes (load/import/save)

---

IPALoader/IPAPlugin.cs

Originally, `IPlugin.OnLevelWasLoaded` is tied to `MonoBehaviour.OnLevelWasLoaded` which only fires when the level is actually reloaded. In newer versions of Unity this seems to be equivalent of loading a scene with `LoadSceneMode.Single` as the load mode.
Since this is unaccounted for in IPALoader, `IPlugin.OnLevelWasLoaded` is being fired
* on any scene change -- even if the level itself wasn't changed
* on scene unloads (with scene level -1)
This causes some IPA plugins (most notably KoikPlugin) prematurely unloading itself and not functioning the same way as in normal IPA install.
This fix simply makes `IPlugin.OnLevelWasLoaded` fire on only full scene loads, simulating the original behaviour of the method. As a result, compatibility with IPA plugins should increase.

Fire OnLevelWasLoaded on actual level load in IPALoader

---

Sideloader/AutoResolver/ResolveInfo.cs
Sideloader/AutoResolver/UniversalAutoResolver.cs

Added CategoryNo to ResolveInfo for use in accessory compatibility resolving. Compatibility resolving for accessories changed to only attempt resolving in for the correct category. Commented out the 'alt-loading' part so compatibility resolving is the default action since it works correctly now.

Fix for accessories compatibility resolving

---

Sideloader/AutoResolver/Hooks.cs
Sideloader/AutoResolver/UniversalAutoResolver.cs
Sideloader/Hooks.cs

On UniversalAutoResolver.cs I changed var intResolve = LoadedResolutionInfo.FirstOrDefault. I actually have no idea how/why this works, but the old way would save a heavily modded character with full sideloader modpack in 40 seconds, new way saves it in 1 second. Left the old way commented out for reference.
On Hooks.cs it's hard to tell what changes were made since I used format document to fix all the whitespace, but in ExtendedCardSave and ExtendedCoordinateSave I added some checks so that the LoadedResolutionInfo list wont be read unless it's likely to be a modded item. Before this change it was accessing it 11 times per accessory, per slot (even if empty), per outfit. Reading through that entire list 1500+ times took a very long time. Now an entire class of lightly modded characters …

Speed up character saving and loading times

---

Sideloader/AutoResolver/Hooks.cs

Prevent resolving for coordinates at Chara Maker start up, male and female cards in Studio in the add character list, coordinates in Studio in the coordinate list.

Prevent resolving for lists where resolution info is never actually used

---

Sideloader/Hooks.cs
Sideloader/Sideloader.cs

If .png files are in a folder and the folder name does not match an existing .unity3d file the textures will never load. By making a list of all folders in sideloader mods that contain .png files and then creating a new asset bundle when needed, such textures will load correctly.

Add asset bundles for folders in sideloader mods that do not match an existing one

---

src/Core_Screencap/Renderers/AlphaShot2.cs

Two changes were made.
- Reflect depth of field on screenshots.
- Transparent through backgrounds on H editing scene and H playing scene in Emotion Creators.
The previous pull request was made by mistake because I didn't get used to using github. I'm sorry.

Fix depth of field. Add transparent scenes in EC.

---

src/Core_Screencap/Core.ScreenshotManager.cs

Changed the maximum for the 'extreme' slider limit to 15360 rather than 15000 to allow for the actual 16k 16:9 resolution.

Changed maximum 'extreme' slider limit

---

src/Core_SliderUnlocker/Core.SliderUnlocker.cs
src/PH_SliderUnlocker/PH.SliderUnlocker.cs

**Issues:** 
* Clicking the default button and trying to move the slider will cause it to get stuck at [-1, 2] range.
~~**Comments:**~~
~~* No idea why that code was there, would be nice to know if it was important for anything because I didn't notice any issues caused by removing it.~~

[PH SliderUnlocker] Fix slider range getting locked to [-1, 2] 

---

src/AI_Screencap/AI.ScreenshotManager.cs

**Observed points:**
* In some scenarios having different shadow cascades might work better than hard-forcing it to 4.
* Ambient occlusion banding doesn't seem to appear when not upsampling.
**Solutions:**
* Added settings for both points.

Added settings for changing shadow cascade override and disabling ambient occlusion

---

src/Core_SliderUnlocker/Core.SliderUnlocker.Math.cs

Fix certain body parts rotating when outside 0-100 range.
The previous fix for PlayHome created some issues with eyes and eyebrow sliders. So I've just hunted the ones which rotated and added a check for them instead, for all the listed games.

[SliderUnlocker] Fix certain body parts rotating when outside 0-100

---

src/Core_Sideloader/UniversalAutoResolver/Core.UAR.StructReference.AI.cs

Had issues with body details randomly failing to load (especially with Hooh Pogskin 1.2) and reverting to default. Noticed when looking at Sideloader debug logging that the ft_detail_b category items weren't showing up in the logs. Went digging and found this. 
I'm now seeing this load the plugin, save and load from cards and generally work as expected.

Sideloader - Body Details not being managed by Sideloader

---

src/AIHS2_Core_Screencap/ScreenshotManager.cs

Non-alpha rendered screenshots now able to capture background color and skybox correctly instead of black background in Maker and Studio. This addresses #92 .
This does not fix a bug with background image not being captured correctly in some cases. No noticeable changes in how screenshot manager behaves in main games.

[AI, HS2] Non-alpha rendered screenshot background fix

---

src/Core_Sideloader/UniversalAutoResolver/Core.UAR.cs

Working with the K1T*s on pulling in custom male heads and skins into AI/HS2. The Illusion fixes PR got the menu option to appear but then we had the issue of the skins not loading for the custom head, traced it into here...
There's code to fix the key reference on female face skins to the corresponding head id after sideloader has assigned the id. Strangely male was left unimplemented. It's...just an exact copy of the female with different category ids.
With this patch added to the other one we've got the male head/skins working fully.

Implement Male Face Skin/Head ID matching in AI/HS2.

---

src/Core_ColorCorrector/Core.ColorCorrector.cs

2 Problems Fixed
- Problem
- Bloom intensity overridden by game on scene initialization, so ColorCorrector configuration does not work
- DefaultBloomStrength does not match KKS Default value

Fix Apply ColorCorrector on Scene initialization in KKS

---

src/Core_Sideloader/UniversalAutoResolver/Core.UAR.Hooks.cs
src/Core_Sideloader/UniversalAutoResolver/Core.UAR.ResolveInfo.cs
src/Core_Sideloader/UniversalAutoResolver/Core.UAR.cs
src/Core_Sideloader_Studio/UniversalAutoResolver/Core.UAR.Studio.Hooks.cs
src/Core_Sideloader_Studio/UniversalAutoResolver/Core.UAR.Studio.StudioPatternResolveInfo.cs
src/Core_Sideloader_Studio/UniversalAutoResolver/Core.UAR.Studio.StudioResolveInfo.cs
src/Core_Sideloader_Studio/UniversalAutoResolver/Core.UAR.Studio.cs

One of the most common help questions with Sideloader based setups is 'Where is this mod?'. Currently only the GUID is exposed to the user who has the card, which is frequently unhelpful in tracking down the source of the mod. 
This PR stores the Author and Website fields of the manifest file alongside the GUID and uses that to fuel better missing/outdated mod warnings.
Obviously this'll rely on mod authors filling in the manifest information and will only read for cards going forward...but hopefully it'll help users to track down mods.

Store author and website alongside the GUID on cards.

---

src/Core_Sideloader/UniversalAutoResolver/Core.UAR.Hooks.cs
src/Core_Sideloader/UniversalAutoResolver/Core.UAR.StructReference.AI.cs
src/Core_Sideloader/UniversalAutoResolver/Core.UAR.StructReference.cs
src/Core_Sideloader/UniversalAutoResolver/Core.UAR.cs

Other categories can be used if a plugin like ClothesToAccessories removes the ao_* only restriction.

[Sideloader] Allow arbitrary categories of accessories instead of only ao_*

---

src/Core_ColorCorrector/Core.ColorCorrector.cs

This makes the plugin effectively no-op with the default settings.
Note that this is a breaking change for users who do use the override. I briefly looked for a way to keep the override enabled when the value has been changed from the default, but I couldn't find a nice way. I hope this isn't too much of a problem.

[ColorCorrector] Don't override bloom stength by default (Fixes #179)

---

src/KKS_ExtensibleSaveFormat/KKS.ExtendedSave.SaveData.Hooks.cs

Please review and merge.
https://github.com/IllusionMods/IllusionFixes/pull/63

[KKS][ExtSave] Avoid error when saving more than 2 GB in the main game

---

src/Core_Screencap/Core.ScreenshotManager.cs

StitchImages has been optimized. 
Please merge it if there are no problems.
The processing time was measured using the code below, and the processing time that used to take 4 seconds was reduced to 0.5 seconds. Depending on the capture parameters, it can be sped up by a factor of 5 to 8.
```
Stopwatch watch = Stopwatch.StartNew();
var result = FlipEyesIn3DCapture.Value ? StitchImages(capture, capture2, 0) : StitchImages(capture2, capture, 0);
System.Console.WriteLine($"@@ {watch.ElapsedMilliseconds}");
```
There is no visible change.
Before:
After:
I think it would be more than 10 times faster if the processing were completed entirely in VRAM, including the argument textures. However, additional VRAM would be required for the buffer.
I refrained from doing so because I knew that people …

[Screencap] StitchImages optimized

---

src/Core_Sideloader_Studio/Core.Sideloader.Studio.cs

Added "mapcategory" to the blacklist, it makes the MapCategory_.csv in a zipmod to work on KKS studio.

[Sideloader][KKS] Add mapcategory to StudioListResolveBlacklist

---

src/AIHS2_Core_Screencap/ScreenshotManager.cs

Completes Issue #210 
Introduces a red frame showing what area of the screen will be captured based on the values set in the screenshot manager.
Example on Screen with Resolution 2560 x 1440:

[Screencap][AI/HS2] Port the tool window + related features from the KK branch

---

src/AIHS2_Core_Screencap/ScreenshotManager.cs

- Fixed #212 
- changed screen capture actions in Update() to asynchronous way
reason why: If video capture is performed in synchronous mode, the program occasionally freezes. Therefore, this process needs to be converted to a message-based asynchronous mode

[Screencap][AI/HS2] Fix "Images overlap when Press F11 quickly"

---

src/AIHS2_Core_Screencap/ScreenshotManager.cs

- Implemented radiating lines, side V lines, and cross guidelines for enhanced screenshot guidance in Tool Window.
- Added buttons for selecting various default screenshot resolutions (HD, FHD, WQHD, 4K, 5K, 8K) in the Tool Window.
- 5K and 8K only visible with ExtremeResolutions Option active in settings

[HS2][Screencap] Add new guideline types and resolution options in Tool Window
